from agents import Agent
    
from search_agent import search_agent_tool
from planner_agent import planner_agent_tool, WebSearchItem, WebSearchPlan
from writer_agent import writer_agent_tool, ReportData
from email_agent import email_agent_tool
import asyncio

# INSTRUCTIONS = (
#     "You are a senior researcher tasked with writing a cohesive report for a research query.\n"
#     "The final output should be in markdown format, and it should be lengthy and detailed. Aim "
#     "for 5-10 pages of content, at least 1000 words.\n"
#     "You will be provided with the original query and should use the following tools to help you gather information and write the report.\n"
#     " 1. Use the 'planner_agent' tool to plan out the searches you need to perform.\n"
#     " 2. Use the 'search_agent' tool to perform web searches based on the plan.\n"
#     " 3. Use the 'writer_agent' tool to write the final report based on the search results.\n"
#     " 4. Use the 'email_agent' tool to send the final report via email.\n"

# )

INSTRUCTIONS = (
    "You are a senior researcher tasked with writing a cohesive report for a research query. "
    "You will be provided with the original query, and use a research assistant to plan searches.\n"
    "Take those planned searches and use a research assistant to perform web searches for each of them. \n"
    "You should then come up with an outline for the report that describes the structure and "
    "flow of the report. Then, generate the report and return that as your final output.\n"
    "The final output should be in markdown format, and it should be lengthy and detailed.\n"
    "Then convert the report into clean, well presented HTML with an appropriate subject line.\n"
    "Send the final report via email in HTML format.\n"
    "Aim for 5-10 pages of content, at least 1000 words\n\n"
    "You should use the following tools to help you gather information and write the report:\n"
    " 1. Use the 'planner_agent' tool to plan out the searches you need to perform.\n"
    " 2. Use the 'search_agent' tool to perform web searches based on the plan.\n"
    " 3. Use the 'writer_agent' tool to write the final report based on the search results.\n"
    " 4. Use the 'email_agent' tool to send the final report generated by the writer_agent via email.\n"
)

research_manager = Agent(
    name="ResearchManager",
    instructions=INSTRUCTIONS,
    tools=[
        search_agent_tool,
        planner_agent_tool,
        writer_agent_tool,
        email_agent_tool
    ],
    model="gpt-4o-mini",
)
